<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="8" ignored="0" total="12" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="27702" started-at="2019-06-19T13:51:51Z" finished-at="2019-06-19T13:52:19Z">
    <groups>
      <group name="major">
        <method signature="ChangeAttributesTests.changeAttributesForRegisteredUser()[pri:0, instance:tests.ChangeAttributesTests@6de30571]" name="changeAttributesForRegisteredUser" class="tests.ChangeAttributesTests"/>
        <method signature="ChangeAttributesTests.changeAttributesForSubscribedUser()[pri:0, instance:tests.ChangeAttributesTests@6de30571]" name="changeAttributesForSubscribedUser" class="tests.ChangeAttributesTests"/>
        <method signature="ChangePasswordTests.changePasswordForRegisteredUser()[pri:0, instance:tests.ChangePasswordTests@489543a6]" name="changePasswordForRegisteredUser" class="tests.ChangePasswordTests"/>
        <method signature="ChangePasswordTests.changePasswordForSubscribedUser()[pri:0, instance:tests.ChangePasswordTests@489543a6]" name="changePasswordForSubscribedUser" class="tests.ChangePasswordTests"/>
      </group> <!-- major -->
      <group name="critical">
        <method signature="FreeRegisterTests.freeRegister()[pri:0, instance:tests.FreeRegisterTests@417d6615]" name="freeRegister" class="tests.FreeRegisterTests"/>
        <method signature="SubscriptionsTests.registration12m()[pri:0, instance:tests.SubscriptionsTests@7a6ebe1e]" name="registration12m" class="tests.SubscriptionsTests"/>
        <method signature="SubscriptionsTests.registration1m()[pri:0, instance:tests.SubscriptionsTests@7a6ebe1e]" name="registration1m" class="tests.SubscriptionsTests"/>
        <method signature="SubscriptionsTests.registration6m()[pri:0, instance:tests.SubscriptionsTests@7a6ebe1e]" name="registration6m" class="tests.SubscriptionsTests"/>
      </group> <!-- critical -->
      <group name="hp">
        <method signature="ContentTests.getContent()[pri:0, instance:tests.ContentTests@5ee34b1b]" name="getContent" class="tests.ContentTests"/>
        <method signature="GetTokenIdTests.getIDToken()[pri:0, instance:tests.GetTokenIdTests@21325036]" name="getIDToken" class="tests.GetTokenIdTests"/>
        <method signature="LoginTests.loginWithRegisteredUser()[pri:0, instance:tests.LoginTests@6272c96f]" name="loginWithRegisteredUser" class="tests.LoginTests"/>
        <method signature="LoginTests.loginWithSubscribedUser()[pri:0, instance:tests.LoginTests@6272c96f]" name="loginWithSubscribedUser" class="tests.LoginTests"/>
      </group> <!-- hp -->
    </groups>
    <test name="Surefire test" duration-ms="27702" started-at="2019-06-19T13:51:51Z" finished-at="2019-06-19T13:52:19Z">
      <class name="tests.LoginTests">
        <test-method status="FAIL" signature="loginWithRegisteredUser()[pri:0, instance:tests.LoginTests@6272c96f]" name="loginWithRegisteredUser" duration-ms="1989" started-at="2019-06-19T13:52:10Z" finished-at="2019-06-19T13:52:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at util.CheckerMethods.getFreeRegisterResponseContent(CheckerMethods.java:59)
at tests.FreeRegisterTests.freeRegister_aroundBody0(FreeRegisterTests.java:64)
at tests.FreeRegisterTests$AjcClosure1.run(FreeRegisterTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.FreeRegisterTests.freeRegister(FreeRegisterTests.java:53)
at tests.LoginTests.loginWithRegisteredUser_aroundBody2(LoginTests.java:40)
at tests.LoginTests$AjcClosure3.run(LoginTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.LoginTests.loginWithRegisteredUser(LoginTests.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithRegisteredUser -->
        <test-method status="FAIL" signature="loginWithSubscribedUser()[pri:0, instance:tests.LoginTests@6272c96f]" name="loginWithSubscribedUser" duration-ms="2544" started-at="2019-06-19T13:52:12Z" finished-at="2019-06-19T13:52:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at util.CheckerMethods.getFreeRegisterResponseContent(CheckerMethods.java:59)
at tests.FreeRegisterTests.freeRegister_aroundBody0(FreeRegisterTests.java:64)
at tests.FreeRegisterTests$AjcClosure1.run(FreeRegisterTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.FreeRegisterTests.freeRegister(FreeRegisterTests.java:53)
at tests.SubscriptionsTests.registration6m_aroundBody2(SubscriptionsTests.java:105)
at tests.SubscriptionsTests$AjcClosure3.run(SubscriptionsTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.SubscriptionsTests.registration6m(SubscriptionsTests.java:99)
at tests.LoginTests.loginWithSubscribedUser_aroundBody0(LoginTests.java:25)
at tests.LoginTests$AjcClosure1.run(LoginTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.LoginTests.loginWithSubscribedUser(LoginTests.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithSubscribedUser -->
      </class> <!-- tests.LoginTests -->
      <class name="tests.FreeRegisterTests">
        <test-method status="PASS" signature="freeRegister()[pri:0, instance:tests.FreeRegisterTests@417d6615]" name="freeRegister" duration-ms="3248" started-at="2019-06-19T13:51:51Z" finished-at="2019-06-19T13:51:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- freeRegister -->
      </class> <!-- tests.FreeRegisterTests -->
      <class name="tests.SubscriptionsTests">
        <test-method status="PASS" signature="registration12m()[pri:0, instance:tests.SubscriptionsTests@7a6ebe1e]" name="registration12m" duration-ms="7582" started-at="2019-06-19T13:51:55Z" finished-at="2019-06-19T13:52:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration12m -->
        <test-method status="FAIL" signature="registration1m()[pri:0, instance:tests.SubscriptionsTests@7a6ebe1e]" name="registration1m" duration-ms="1390" started-at="2019-06-19T13:52:02Z" finished-at="2019-06-19T13:52:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at util.CheckerMethods.getFreeRegisterResponseContent(CheckerMethods.java:59)
at tests.FreeRegisterTests.freeRegister_aroundBody0(FreeRegisterTests.java:64)
at tests.FreeRegisterTests$AjcClosure1.run(FreeRegisterTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.FreeRegisterTests.freeRegister(FreeRegisterTests.java:53)
at tests.SubscriptionsTests.registration1m_aroundBody0(SubscriptionsTests.java:64)
at tests.SubscriptionsTests$AjcClosure1.run(SubscriptionsTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.SubscriptionsTests.registration1m(SubscriptionsTests.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration1m -->
        <test-method status="FAIL" signature="registration6m()[pri:0, instance:tests.SubscriptionsTests@7a6ebe1e]" name="registration6m" duration-ms="821" started-at="2019-06-19T13:52:04Z" finished-at="2019-06-19T13:52:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at util.CheckerMethods.getFreeRegisterResponseContent(CheckerMethods.java:59)
at tests.FreeRegisterTests.freeRegister_aroundBody0(FreeRegisterTests.java:64)
at tests.FreeRegisterTests$AjcClosure1.run(FreeRegisterTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.FreeRegisterTests.freeRegister(FreeRegisterTests.java:53)
at tests.SubscriptionsTests.registration6m_aroundBody2(SubscriptionsTests.java:105)
at tests.SubscriptionsTests$AjcClosure3.run(SubscriptionsTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.SubscriptionsTests.registration6m(SubscriptionsTests.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration6m -->
      </class> <!-- tests.SubscriptionsTests -->
      <class name="tests.ChangePasswordTests">
        <test-method status="FAIL" signature="changePasswordForRegisteredUser()[pri:0, instance:tests.ChangePasswordTests@489543a6]" name="changePasswordForRegisteredUser" duration-ms="2140" started-at="2019-06-19T13:52:05Z" finished-at="2019-06-19T13:52:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at util.CheckerMethods.getFreeRegisterResponseContent(CheckerMethods.java:59)
at tests.FreeRegisterTests.freeRegister_aroundBody0(FreeRegisterTests.java:64)
at tests.FreeRegisterTests$AjcClosure1.run(FreeRegisterTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.FreeRegisterTests.freeRegister(FreeRegisterTests.java:53)
at tests.ChangePasswordTests.changePasswordForRegisteredUser_aroundBody0(ChangePasswordTests.java:28)
at tests.ChangePasswordTests$AjcClosure1.run(ChangePasswordTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.ChangePasswordTests.changePasswordForRegisteredUser(ChangePasswordTests.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePasswordForRegisteredUser -->
        <test-method status="FAIL" signature="changePasswordForSubscribedUser()[pri:0, instance:tests.ChangePasswordTests@489543a6]" name="changePasswordForSubscribedUser" duration-ms="2957" started-at="2019-06-19T13:52:07Z" finished-at="2019-06-19T13:52:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at util.CheckerMethods.getFreeRegisterResponseContent(CheckerMethods.java:59)
at tests.FreeRegisterTests.freeRegister_aroundBody0(FreeRegisterTests.java:64)
at tests.FreeRegisterTests$AjcClosure1.run(FreeRegisterTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.FreeRegisterTests.freeRegister(FreeRegisterTests.java:53)
at tests.SubscriptionsTests.registration6m_aroundBody2(SubscriptionsTests.java:105)
at tests.SubscriptionsTests$AjcClosure3.run(SubscriptionsTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.SubscriptionsTests.registration6m(SubscriptionsTests.java:99)
at tests.ChangePasswordTests.changePasswordForSubscribedUser_aroundBody2(ChangePasswordTests.java:48)
at tests.ChangePasswordTests$AjcClosure3.run(ChangePasswordTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.ChangePasswordTests.changePasswordForSubscribedUser(ChangePasswordTests.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePasswordForSubscribedUser -->
      </class> <!-- tests.ChangePasswordTests -->
      <class name="tests.ContentTests">
        <test-method status="PASS" signature="getContent()[pri:0, instance:tests.ContentTests@5ee34b1b]" name="getContent" duration-ms="4" started-at="2019-06-19T13:52:19Z" finished-at="2019-06-19T13:52:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getContent -->
      </class> <!-- tests.ContentTests -->
      <class name="tests.GetTokenIdTests">
        <test-method status="PASS" signature="getIDToken()[pri:0, instance:tests.GetTokenIdTests@21325036]" name="getIDToken" duration-ms="217" started-at="2019-06-19T13:52:05Z" finished-at="2019-06-19T13:52:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getIDToken -->
      </class> <!-- tests.GetTokenIdTests -->
      <class name="tests.ChangeAttributesTests">
        <test-method status="FAIL" signature="changeAttributesForRegisteredUser()[pri:0, instance:tests.ChangeAttributesTests@6de30571]" name="changeAttributesForRegisteredUser" duration-ms="2321" started-at="2019-06-19T13:52:14Z" finished-at="2019-06-19T13:52:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at util.CheckerMethods.getFreeRegisterResponseContent(CheckerMethods.java:59)
at tests.FreeRegisterTests.freeRegister_aroundBody0(FreeRegisterTests.java:64)
at tests.FreeRegisterTests$AjcClosure1.run(FreeRegisterTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.FreeRegisterTests.freeRegister(FreeRegisterTests.java:53)
at tests.ChangeAttributesTests.changeAttributesForRegisteredUser_aroundBody2(ChangeAttributesTests.java:50)
at tests.ChangeAttributesTests$AjcClosure3.run(ChangeAttributesTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.ChangeAttributesTests.changeAttributesForRegisteredUser(ChangeAttributesTests.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changeAttributesForRegisteredUser -->
        <test-method status="FAIL" signature="changeAttributesForSubscribedUser()[pri:0, instance:tests.ChangeAttributesTests@6de30571]" name="changeAttributesForSubscribedUser" duration-ms="2292" started-at="2019-06-19T13:52:17Z" finished-at="2019-06-19T13:52:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected [Test] but found [null],
expected [Test] but found [null],
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null,
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at util.CheckerMethods.getFreeRegisterResponseContent(CheckerMethods.java:59)
at tests.FreeRegisterTests.freeRegister_aroundBody0(FreeRegisterTests.java:64)
at tests.FreeRegisterTests$AjcClosure1.run(FreeRegisterTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.FreeRegisterTests.freeRegister(FreeRegisterTests.java:53)
at tests.SubscriptionsTests.registration6m_aroundBody2(SubscriptionsTests.java:105)
at tests.SubscriptionsTests$AjcClosure3.run(SubscriptionsTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.SubscriptionsTests.registration6m(SubscriptionsTests.java:99)
at tests.ChangeAttributesTests.changeAttributesForSubscribedUser_aroundBody0(ChangeAttributesTests.java:28)
at tests.ChangeAttributesTests$AjcClosure1.run(ChangeAttributesTests.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at tests.ChangeAttributesTests.changeAttributesForSubscribedUser(ChangeAttributesTests.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changeAttributesForSubscribedUser -->
      </class> <!-- tests.ChangeAttributesTests -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
